version: 0.2
phases:
  install:
    commands:
      # needed for latest awscli
      - echo "executing install commands"
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo "executing pre_build commands"
      - cd imagine-universal; npm install; npm run build:ssr; cd ..
  build:
    commands:
      - echo "executing build commands"
      - docker-compose build
  post_build:
    commands:
      - echo "executing post_build commands"
      - docker-compose push
