version: "2"
services:
  imagine-server:
    image: 398088795386.dkr.ecr.eu-west-1.amazonaws.com/imagine/imagine-server:devel
    build: ./imagine-server/
    ports:
      - "4000:4000"
    links:
      - mongo
  imagine-universal:
    image: 398088795386.dkr.ecr.eu-west-1.amazonaws.com/imagine/imagine-universal:devel
    build: ./imagine-universal/
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
